### ISSUE TITLE
Plugins loading order

### ISSUE THREAD

**Issue by hoshiryu** [STORM-IRIT/Radium-Engine#489] opened 2020-01-10 16:40 UTC
I have private plugins that depend on official ones, and need to be loaded after these.
However, the main-app doesn't load the plugin in the order specified as argument with the `-l` option.
Instead, it just checks, for each file in the Plugins directory (taken in alphabetic order), if it must be loaded or not.
There could be multiple solutions to this issue:
 - Specifying in the Plugins documentation (which has to be done/updated) that each Plugin should be independent from the others. This seems legit, but first we have to way to ensure that; and second this would enforce plugin developers to integrate/adapt existing plugins into theirs, which is not viable.
 - Ensuring that the plugins are loaded in the given order. But then, what about adding/removing plugins "on the fly"?
 - (if you have other possible solutions, fill free to give details)

**Comment by MathiasPaulin** [comment] 2020-01-10 16:52
An other possible solution :  
After loading, when calling registerPlugin, the plugins must only populate a "prerequestList" to declare from which other plugin(s) it depends, and do nothing else. 
Then, the loader build a priorityList from this prerequisiteList and call "initializePlugin" in the order of priority. initializePlugin is in charge of populating the Radium ecosystem with the functionalities of the plugin (what is done now in registerPlugin).
If a plugin is not declared as a prerequest from another, and so does not appear in the priorityList, it is loaded after every other plugins (in lexicographical order)

And, related to this issue, thereis no developer manual for Plugins. Only reference manual ...

**Comment by nmellado** [comment] 2020-01-10 20:45
For now, everything is designed so that the plugins should have no inter-dependency.
It is true that we have a the skinning and animation plugins that break that concept, but should be fixed soon.
It is true that the documentation needs to be fixed.

I don' t see why we need to allow plugins to depend to each other. For me a plugin is a self contained add-on. So when we have two plugins that need to share something, it means either that this something could be moved to Radium libs, or that the two plugins need to be merged. Of course I might also be wrong, so feel free to explain any concrete scenario that would require a deferred loading as suggested.

**Comment by MathiasPaulin** [comment] 2020-01-12 11:45
I agree that the animation-skinning plugin will soon be in the core. But the problem is more general than that.
And I disagree that plugins must be independent from others. Plugins are a way to add functionalities to the Radium ecosystem and one plugin might depend on other(s) to develop its functionality. And not all plugins can be integrated into the Core or Engine.

Imagine that a developper publish a plugin that extends the Radium Material Library to add, amongst others, the "principle BSDF" (aka Disney BRDF). 
Another developper, seeing that, submit a plugin that use this to propose a realistic realtime ray tracer. But, in order to reuse existing code instead of developing twice the wheel, he wants to have a dependency on this plugin. If the first plugin is not loaded, the second could not be loaded neither. 
Putting the extension of the material library in Radium Core might take a while and the first developper do not want to be a core Radium developper.
The second developper, not the same person than the first, wants to benefit of the evolutions and improvements of the first Plugin, without maintaining his own version of the code. His plugin just wants to verify that a given functionality is available and will refuse to load if not present (with a message asking to install the required functionality). So the two plugins can't be merged.

**Comment by nmellado** [comment] 2020-03-25 20:36
This does not follow the concept we designed for the plugins in Radium.

Currently, plugins can be seen as wiring tools to extend the Radium libraries/applications. If they contain something that could be of interest for other plugins, they can exposed them in a dedicated library.
You can simply have a library provided alongside the plugin A which exposes your material, and that could be linked with plugin B.
Also, this design will force the developer of the library to have a generic design, which should facilitate its integration in Radium libraries. Another way to say it is: what you put in your plugin is your own mess, but what you expose in your library need to be clean and reliable if you want other people to use it.

If we want to change this, as you suggest, and allow inter-plugins relations, then we need to clearly state what is possible or not, and add mechanisms in the API to explicitly allow such kind of usage. Also, we will have to ensure that the code quality of the plugins meet Radium standards.

From my point of view, I don't see why adding inter-plugin relations would be beneficial (in comparison with using intermediate compact libs and/or adding content to Radium libs). In the other hand, it is clear that adding this functionality will cost development time.

**Comment by MathiasPaulin** [comment] 2020-06-19 06:56
Solved by merged PR #550. 
By allowing to split plugins into a library thad defines functionalities and a plugin that defines the interface between an app and the library, PR #550 solved this issue. If your plugin depends on the functionalities defined by another one, it does not depends on the plugin but on the lib. So just include the lib header and link it with the lib. 
See `ExamplePluginWithLib` in the `test` directory of the Radium master.

**Closed by MathiasPaulin** 2020-06-19 06:56 UTC
Labels: question
